spring:
  application:
    name: K-BI-Backend
  profiles:
    active: dev
  # swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session
  session:
    # store-type: redis
    # 30 days
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaka
    username: root
    password: 196851444
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
server:
  address: 0.0.0.0
  port: 8108
  servlet:
    context-path: /api
    # cookie 30 days
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# AI Api
yuapi:
  client:
    access-key: 2x09q06lnkyekzzj5yzpvo21tj0867q4
    secret-key: pmj5w0zbf9e96b0ev6sgzmpn28q1bdek
openAI:
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo

wx:
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  open:
    appId: xxx
    appSecret: xxx
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx